after-login-command = []
after-startup-command = []
start-at-login = true

[gaps]
inner.horizontal = 3
inner.vertical = 3
outer.left = 6
outer.right = 6
outer.top = 6
outer.bottom = 6

[mode.main.binding]
alt-left        = 'focus left'
alt-right       = 'focus right'
alt-up          = 'focus up'
alt-down        = 'focus down'
alt-shift-left  = 'move left'
alt-shift-right = 'move right'
alt-shift-up    = 'move up'
alt-shift-down  = 'move down'
alt-q           = 'close'
alt-f           = 'fullscreen'
alt-v           = 'layout floating tiling'
alt-j           = 'layout tiles horizontal vertical'
alt-shift-r     = 'reload-config'
alt-enter       = 'exec-and-forget /usr/bin/open -a Ghostty'
alt-b           = 'exec-and-forget /usr/bin/open -a "Brave Browser"'
alt-1           = 'workspace 1'
alt-2           = 'workspace 2'
alt-3           = 'workspace 3'
alt-4           = 'workspace 4'
alt-5           = 'workspace 5'
alt-6           = 'workspace 6'
alt-7           = 'workspace 7'
alt-8           = 'workspace 8'
alt-9           = 'workspace 9'
alt-shift-1     = 'move-node-to-workspace 1'
alt-shift-2     = 'move-node-to-workspace 2'
alt-shift-3     = 'move-node-to-workspace 3'
alt-shift-4     = 'move-node-to-workspace 4'
alt-shift-5     = 'move-node-to-workspace 5'
alt-shift-6     = 'move-node-to-workspace 6'
alt-shift-7     = 'move-node-to-workspace 7'
alt-shift-8     = 'move-node-to-workspace 8'
alt-shift-9     = 'move-node-to-workspace 9'
