#!/usr/bin/env bash
# Usage: bash ~/dotfiles/scripts/switch-theme.sh <theme>

set -e
THEME="$1"
DOTFILES="$HOME/dotfiles"
THEMES_DIR="$DOTFILES/themes"

if [ -z "$THEME" ]; then
    echo "Available: $(ls $THEMES_DIR/*.sh | xargs -n1 basename | sed 's/.sh//' | tr '\n' ' ')"
    exit 1
fi

if [ ! -f "$THEMES_DIR/$THEME.sh" ]; then
    echo "Theme '$THEME' not found."
    exit 1
fi

source "$THEMES_DIR/$THEME.sh"
echo "Switching to: $THEME_NAME"

# ── Hyprland border colors (sourced by hyprland.conf; never edits the tracked
#    config — see colors.conf.base / SETUP-NOTES) ───────────────────────────
if [[ "$(uname)" == "Linux" ]]; then
cat > "$HOME/.config/hypr/colors.conf" << EOF
# Generated by switch-theme.sh ($THEME_NAME) — DO NOT EDIT
\$border_active_1 = rgba(${BORDER_ACTIVE_1}ff)
\$border_active_2 = rgba(${BORDER_ACTIVE_2}ff)
\$border_inactive = rgba(${BORDER_INACTIVE}aa)
EOF
    hyprctl reload
fi

# ── Waybar CSS (hex only, no rgb conversion) ──────────────────────
if [[ "$(uname)" == "Linux" ]]; then
cat > "$HOME/.config/waybar/style.css" << EOF
* {
    font-family: "JetBrainsMono Nerd Font", "JetBrainsMono NF", "Font Awesome 6 Free", monospace;
    font-size: 13px;
    font-weight: 500;
    min-height: 0;
    border: none;
    border-radius: 0;
}
window#waybar {
    background: transparent;
    color: #${FG_DIM};
}
.modules-left, .modules-center, .modules-right {
    background: #${BAR_BG};
    border: 1px solid #${BAR_BORDER};
    border-radius: 10px;
    margin: 6px 4px;
    padding: 0 6px;
}
#workspaces { padding: 0 4px; }
/* base = occupied: bright chip so windows-elsewhere are visible at a glance */
#workspaces button {
    padding: 0 8px;
    margin: 4px 2px;
    color: #${FG_BRIGHT};
    background: #${BG_MID};
    border-radius: 6px;
    transition: all 0.2s ease;
}
/* empty persistent workspaces: dim, no chip */
#workspaces button.empty {
    color: #${BAR_INACTIVE_WS};
    background: transparent;
}
/* active must come after .empty: an empty focused workspace has both classes */
#workspaces button.active {
    color: #${BG_DARK};
    background: #${ACCENT_PRIMARY};
}
#workspaces button.urgent {
    color: #${BG_DARK};
    background: #${RED};
}
#workspaces button:hover {
    background: #${BG_LIGHT};
    color: #${FG_BRIGHT};
}
#clock {
    padding: 0 14px;
    color: #${ACCENT_PRIMARY};
    font-weight: 600;
}
#cpu, #memory, #disk, #network, #pulseaudio, #battery, #tray {
    padding: 0 10px;
    margin: 4px 3px;
    background: #${BG_MID};
    color: #${FG_DIM};
    border-radius: 6px;
    transition: all 0.2s ease;
}
#cpu:hover, #memory:hover, #disk:hover, #network:hover, #pulseaudio:hover, #battery:hover {
    background: #${BG_LIGHT};
}
#cpu { color: #${YELLOW}; }
#memory { color: #${ORANGE}; }
#disk { color: #${PURPLE}; }
#network { color: #${GREEN}; }
#pulseaudio { color: #${TEAL}; }
#pulseaudio.muted { color: #${RED}; }
#battery { color: #${ACCENT_PRIMARY}; }
#battery.warning { color: #${YELLOW}; }
#battery.critical { color: #${RED}; }
#tray { padding: 0 8px; }
tooltip {
    background: #${BG_DARK};
    border: 1px solid #${BG_LIGHTER};
    border-radius: 8px;
    color: #${FG_BRIGHT};
    padding: 4px;
}
EOF
fi

# ── foot terminal ─────────────────────────────────────────────────
if [[ "$(uname)" == "Linux" ]]; then
cat > "$HOME/.config/foot/foot.ini" << EOF
font=JetBrainsMono Nerd Font:size=11
pad=12x12
dpi-aware=yes

[cursor]
style=beam

[colors-dark]
alpha=0.95
background=${BG_DARK}
foreground=${FG_DIM}
selection-background=${BG_LIGHT}
selection-foreground=${FG_BRIGHT}
regular0=${BG_MID}
regular1=${RED}
regular2=${GREEN}
regular3=${YELLOW}
regular4=${ACCENT_SECONDARY}
regular5=${PURPLE}
regular6=${TEAL}
regular7=${FG_MID}
bright0=${BG_LIGHTER}
bright1=${RED}
bright2=${GREEN}
bright3=${YELLOW}
bright4=${ACCENT_PRIMARY}
bright5=${PURPLE}
bright6=${ACCENT_PRIMARY}
bright7=${FG_BRIGHT}
EOF
    # Scratchpad terminals bake colors at spawn — kill them so pyprland
    # respawns with the new foot.ini/btop theme on next toggle
    pkill -f '^foot --app-id=dropdown-' 2>/dev/null || true
fi

# ── Ghostty terminal (config statically references theme=active; we only write
#    the gitignored active palette file — like btop) ───────────────────────
GHOSTTY_THEMES_DIR="$HOME/.config/ghostty/themes"
mkdir -p "$GHOSTTY_THEMES_DIR"
cat > "$GHOSTTY_THEMES_DIR/active" << EOF
palette = 0=#${BG_MID}
palette = 1=#${RED}
palette = 2=#${GREEN}
palette = 3=#${YELLOW}
palette = 4=#${ACCENT_SECONDARY}
palette = 5=#${PURPLE}
palette = 6=#${TEAL}
palette = 7=#${FG_MID}
palette = 8=#${BG_LIGHTER}
palette = 9=#${RED}
palette = 10=#${GREEN}
palette = 11=#${YELLOW}
palette = 12=#${ACCENT_PRIMARY}
palette = 13=#${PURPLE}
palette = 14=#${ACCENT_PRIMARY}
palette = 15=#${FG_BRIGHT}
background = #${BG_DARK}
foreground = #${FG_DIM}
cursor-color = #${ACCENT_PRIMARY}
selection-background = #${BG_LIGHT}
selection-foreground = #${FG_BRIGHT}
EOF

# ── hyprlock ──────────────────────────────────────────────────────
if [[ "$(uname)" == "Linux" ]]; then
cat > "$HOME/.config/hypr/hyprlock.conf" << EOF
auth {
    fingerprint {
        enabled = true
    }
}
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    contrast = 0.9
    brightness = 0.8
}
input-field {
    monitor =
    size = 280, 56
    outline_thickness = 2
    dots_size = 0.28
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(${ACCENT_PRIMARY}ff)
    inner_color = rgba(${BG_DARK}b3)
    font_color = rgba(${FG_DIM}ff)
    fade_on_empty = false
    placeholder_text = <i>password...</i>
    hide_input = false
    rounding = 12
    check_color = rgba(${GREEN}ff)
    fail_color = rgba(${RED}ff)
    position = 0, -140
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] date "+%I:%M %p"
    color = rgba(${FG_BRIGHT}ff)
    font_size = 110
    font_family = JetBrainsMono NF ExtraBold
    position = 0, 120
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:60000] date "+%A, %B %d"
    color = rgba(${ACCENT_PRIMARY}ff)
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position = 0, 30
    halign = center
    valign = center
}
label {
    monitor =
    text = \$USER
    color = rgba(${FG_DIM}e6)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -240
    halign = center
    valign = center
}
EOF
fi

# ── Fix GTK CSS alpha + restart waybar ───────────────────────────
if [[ "$(uname)" == "Linux" ]]; then
    sed -i "s/background: #\([0-9a-fA-F]\{6\}\)ee;/background: alpha(#\1, 0.93);/g" "$HOME/.config/waybar/style.css"
    sed -i "s/background: #\([0-9a-fA-F]\{6\}\)99;/background: alpha(#\1, 0.60);/g" "$HOME/.config/waybar/style.css"
    sed -i "s/background: #\([0-9a-fA-F]\{6\}\)fa;/background: alpha(#\1, 0.98);/g" "$HOME/.config/waybar/style.css"
    pkill waybar 2>/dev/null; sleep 1 && waybar &>/dev/null & disown
fi

# ── Mako notifications ────────────────────────────────────────────
if [[ "$(uname)" == "Linux" ]]; then
    mkdir -p "$HOME/.config/mako"
    cat > "$HOME/.config/mako/config" << EOF
background-color=#${BG_DARK}ff
text-color=#${FG_BRIGHT}ff
border-color=#${ACCENT_PRIMARY}ff
border-size=2
border-radius=8
padding=12
margin=8
default-timeout=5000
max-visible=5
EOF
    makoctl reload 2>/dev/null || true
fi

# ── btop ──────────────────────────────────────────────────────────
if [[ "$(uname)" == "Linux" ]]; then
    BTOP_THEMES_DIR="$HOME/.config/btop/themes"
    mkdir -p "$BTOP_THEMES_DIR"
    if [ -f "$DOTFILES/btop/.config/btop/themes/$THEME.theme" ]; then
        cp "$DOTFILES/btop/.config/btop/themes/$THEME.theme" "$BTOP_THEMES_DIR/active.theme"
    fi
    BTOP_CONF="$HOME/.config/btop/btop.conf"
    if [ -f "$BTOP_CONF" ]; then
        if grep -q "^color_theme" "$BTOP_CONF"; then
            sed -i 's/^color_theme.*$/color_theme = "active"/' "$BTOP_CONF"
        else
            echo 'color_theme = "active"' >> "$BTOP_CONF"
        fi
    fi
fi

# ── Fuzzel app launcher ───────────────────────────────────────────
if [[ "$(uname)" == "Linux" ]]; then
    mkdir -p "$HOME/.config/fuzzel"
    cat > "$HOME/.config/fuzzel/fuzzel.ini" << EOF
[main]
font=JetBrainsMono Nerd Font:size=13
terminal=foot {cmd}
width=30
lines=8
tabs=2
horizontal-pad=20
vertical-pad=10
inner-pad=8

[colors]
background=${BG_DARK}ff
text=${FG_DIM}ff
match=${ACCENT_PRIMARY}ff
selection=${BG_LIGHT}cc
selection-text=${FG_BRIGHT}ff
border=${ACCENT_PRIMARY}ff

[border]
width=2
radius=8
EOF
    pkill fuzzel 2>/dev/null || true
fi

# ── Fastfetch keyColor + DU logo colors ──────────────────────────
FASTFETCH_CONF="$HOME/.config/fastfetch/config.jsonc"
if [ -f "$FASTFETCH_CONF" ]; then
    if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' "s/\"color\": \"#[0-9a-fA-F]*\"/\"color\": \"#${ACCENT_PRIMARY}\"/" "$FASTFETCH_CONF"
        sed -i '' "s/\"1\": \"#[0-9a-fA-F]*\"/\"1\": \"#${ACCENT_PRIMARY}\"/" "$FASTFETCH_CONF"
        sed -i '' "s/\"2\": \"#[0-9a-fA-F]*\"/\"2\": \"#${RED}\"/" "$FASTFETCH_CONF"
    else
        sed -i "s/\"color\": \"#[0-9a-fA-F]*\"/\"color\": \"#${ACCENT_PRIMARY}\"/" "$FASTFETCH_CONF"
        sed -i "s/\"1\": \"#[0-9a-fA-F]*\"/\"1\": \"#${ACCENT_PRIMARY}\"/" "$FASTFETCH_CONF"
        sed -i "s/\"2\": \"#[0-9a-fA-F]*\"/\"2\": \"#${RED}\"/" "$FASTFETCH_CONF"
    fi
fi

# ── GTK3/GTK4 (adw-gtk3 + libadwaita named colors, Gradience-style) ──
if [[ "$(uname)" == "Linux" ]]; then
    mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"
    GTK_CSS="/* Generated by switch-theme.sh ($THEME_NAME) — DO NOT EDIT */
@define-color accent_color #${ACCENT_PRIMARY};
@define-color accent_bg_color #${ACCENT_PRIMARY};
@define-color accent_fg_color #${BG_DARK};
@define-color window_bg_color #${BG_DARK};
@define-color window_fg_color #${FG_BRIGHT};
@define-color view_bg_color #${BG_DARK};
@define-color view_fg_color #${FG_BRIGHT};
@define-color headerbar_bg_color #${BG_MID};
@define-color headerbar_fg_color #${FG_BRIGHT};
@define-color headerbar_backdrop_color #${BG_DARK};
@define-color headerbar_border_color #${BG_LIGHTER};
@define-color sidebar_bg_color #${BG_MID};
@define-color sidebar_fg_color #${FG_BRIGHT};
@define-color sidebar_backdrop_color #${BG_DARK};
@define-color secondary_sidebar_bg_color #${BG_MID};
@define-color secondary_sidebar_fg_color #${FG_BRIGHT};
@define-color card_bg_color #${BG_MID};
@define-color card_fg_color #${FG_BRIGHT};
@define-color dialog_bg_color #${BG_MID};
@define-color dialog_fg_color #${FG_BRIGHT};
@define-color popover_bg_color #${BG_MID};
@define-color popover_fg_color #${FG_BRIGHT};
@define-color destructive_bg_color #${RED};
@define-color destructive_fg_color #${BG_DARK};
@define-color destructive_color #${RED};
@define-color success_color #${GREEN};
@define-color warning_color #${YELLOW};
@define-color error_color #${RED};"
    echo "$GTK_CSS" > "$HOME/.config/gtk-3.0/gtk.css"
    echo "$GTK_CSS" > "$HOME/.config/gtk-4.0/gtk.css"
fi

# ── zsh prompt (p10k overrides, sourced from .zshrc after .p10k.zsh) ──
mkdir -p "$HOME/.config/zsh"
cat > "$HOME/.config/zsh/prompt-colors.zsh" << EOF
# Generated by switch-theme.sh ($THEME_NAME) — DO NOT EDIT
# Hex colors need a truecolor terminal (foot/ghostty: yes).
typeset -g POWERLEVEL9K_BACKGROUND='#${BG_MID}'
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#${FG_BRIGHT}'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#${ACCENT_PRIMARY}'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#${FG_DIM}'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#${ACCENT_PRIMARY}'
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#${GREEN}'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#${GREEN}'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#${YELLOW}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#${GREEN}'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#${RED}'
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#${GREEN}'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='#${GREEN}'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#${RED}'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#${RED}'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#${RED}'
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#${YELLOW}'
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='#${FG_MID}'
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='#${RED}'
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#${FG_DIM}'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND='#${BG_LIGHTER}'
EOF

# ── Greeter staging (applied separately: sudo sh scripts/greeter-apply.sh) ──
if [[ "$(uname)" == "Linux" ]]; then
    bash "$DOTFILES/scripts/stage-greeter-theme.sh" "$ACCENT_PRIMARY" || true
fi

# ── Save current theme ────────────────────────────────────────────
echo "$THEME" > "$HOME/.config/current-theme"

echo "✓ Switched to: $THEME_NAME"
echo "  borders reloaded · waybar restarted · foot updated · ghostty updated · hyprlock updated"
echo "  mako updated · btop theme updated · fuzzel updated · fastfetch updated"
