typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
[[ $- == *i* ]] && fastfetch
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting zoxide)

source $ZSH/oh-my-zsh.sh

# User configuration

# QoL aliases (post-migration to Fedora)
alias cat='bat --paging=never'
alias ls='eza --icons --group-directories-first'
alias ll='eza -l --icons --group-directories-first --git'
alias la='eza -la --icons --group-directories-first --git'
alias find='fd'

# Rocket League OFFLINE training with BakkesMod (-noeac). Online ranked/casual
# stays on the Heroic Play button, untouched.
alias rl-train='$HOME/.local/bin/rl-train.sh'

eval "$(zoxide init zsh)"
[ -f /usr/share/fzf/shell/key-bindings.zsh ] && source /usr/share/fzf/shell/key-bindings.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Theme-managed prompt colors (regenerated by scripts/switch-theme.sh)
[[ ! -f ~/.config/zsh/prompt-colors.zsh ]] || source ~/.config/zsh/prompt-colors.zsh

# uv env loader (uncomment after installing uv)
# . "$HOME/.local/bin/env"

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

# Go binaries
export PATH=$PATH:$HOME/go/bin

export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Rocket League BakkesMod training
alias rl-train='$HOME/.local/bin/rl-train.sh'
alias rl-map-extract='$HOME/.local/bin/rl-map-extract.sh'
alias rl-map-download='$HOME/.local/bin/rl-map-download.sh'
