typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
# Width-aware fetch. Side-by-side (logo left, info right) needs ~82 cols before
# the info column starts wrapping into a mess; below that — a tiling WM giving
# foot half the screen — stack the logo ON TOP so the info gets the full width
# and never wraps. The 29-col "du" logo + padding + longest info line is the 82.
ff() {
  if [[ ${COLUMNS:-80} -lt 82 ]]; then fastfetch --logo-position top
  else fastfetch; fi
}
[[ $- == *i* ]] && ff
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting zoxide)

source $ZSH/oh-my-zsh.sh

# User configuration

# QoL aliases (post-migration to Fedora)
alias cat='bat --paging=never'
alias ls='eza --icons --group-directories-first'
alias ll='eza -l --icons --group-directories-first --git'
alias la='eza -la --icons --group-directories-first --git'
alias find='fd'

# Rocket League OFFLINE training with BakkesMod (-noeac). Online ranked/casual
# stays on the Heroic Play button, untouched.
alias rl-train='$HOME/.local/bin/rl-train.sh'

eval "$(zoxide init zsh)"
[ -f /usr/share/fzf/shell/key-bindings.zsh ] && source /usr/share/fzf/shell/key-bindings.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Theme-managed prompt colors (regenerated by scripts/switch-theme.sh)
[[ ! -f ~/.config/zsh/prompt-colors.zsh ]] || source ~/.config/zsh/prompt-colors.zsh

# uv env loader (uncomment after installing uv)
# . "$HOME/.local/bin/env"

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

# Go binaries
export PATH=$PATH:$HOME/go/bin

export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Rocket League BakkesMod training
alias rl-train='$HOME/.local/bin/rl-train.sh'
alias rl-map-extract='$HOME/.local/bin/rl-map-extract.sh'
alias rl-map-download='$HOME/.local/bin/rl-map-download.sh'

# Cross-machine work awareness (Syncthing-shared ~/code heartbeats)
alias work-status='$HOME/dotfiles/scripts/work-status.sh'

# Grok Build: regenerate vault SessionStart context BEFORE the TUI loads, so
# ~/.grok/rules/brain-session-context.md is this launch, not last session.
# SessionStart cannot inject into the same session (probed); this wrapper is
# the same-session-freshness path. `command grok` skips the function.
#
# Never give the agent $HOME (or the old ~/Brain clone) as cwd — Grok 0.2.93
# tarball blast radius. A fresh terminal starts in ~; type `grok` anyway.
# Your shell stays put; only the agent process is launched from ~/grok-sandbox.
# If you already `cd`'d into a project, that project stays the cwd.
grok() {
  if [ -x "$HOME/dotfiles/scripts/claude-brain-context.sh" ]; then
    printf '%s' '{"source":"startup","hookEventName":"session_start"}' \
      | GROK_HOOK_EVENT=session_start "$HOME/dotfiles/scripts/claude-brain-context.sh" \
      >/dev/null 2>&1 || true
  fi
  if [ "${1-}" = "trace" ]; then
    local has_local=0 a
    for a in "$@"; do
      [ "$a" = "--local" ] && has_local=1
    done
    if [ "$has_local" -eq 0 ]; then
      echo "grok wrapper: refusing remote trace upload; adding --local" >&2
      set -- "$@" --local
    fi
  fi
  local launch_cwd="$PWD"
  local home_abs="${HOME:A}"
  local here="${PWD:A}"
  local sandbox="$HOME/grok-sandbox"
  case "$here" in
    "$home_abs"|"$home_abs/Brain"|"$home_abs/Brain.linux-mint-archive-2026-05"|"$home_abs/Brain.linux-mint-archive-2026-05"/*)
      mkdir -p "$sandbox"
      launch_cwd="$sandbox"
      echo "grok wrapper: launching in ~/grok-sandbox (agent cwd; your shell stays in ${PWD/#$HOME/~})" >&2
      ;;
  esac
  (cd "$launch_cwd" && command grok "$@")
}

# ── QoL tooling (2026-07-17) ─────────────────────────────────────────────────
# Each guarded so the shell still starts fine on a machine missing the tool.
alias lg='lazygit'
command -v dust >/dev/null 2>&1 && alias du='dust'      # tree-style disk usage
command -v duf  >/dev/null 2>&1 && alias df='duf'       # prettier df
command -v procs >/dev/null 2>&1 && alias ps='procs'    # modern ps
# direnv — per-project env auto-loading
command -v direnv >/dev/null 2>&1 && eval "$(direnv hook zsh)"
# atuin — encrypted, cross-machine shell history (binds Ctrl-R + Up).
# Sourced LAST so it wins the Ctrl-R binding over fzf/oh-my-zsh.
command -v atuin >/dev/null 2>&1 && eval "$(atuin init zsh)"

# jot — capture a thought into the Obsidian brain from anywhere: jot buy cables
jot() { "$HOME/dotfiles/scripts/jot.sh" "$@"; }
export YDOTOOL_SOCKET="$XDG_RUNTIME_DIR/.ydotool_socket"

# Local secrets — deliberately OUTSIDE ~/dotfiles, which auto-commits and pushes
# every 15 minutes. Never put a key in the dotfiles repo. chmod 600.
[ -f ~/.config/secrets.env ] && source ~/.config/secrets.env

# ── Keep the fastfetch "du" logo crisp across resizes ────────────────────────
# fastfetch prints its ASCII logo once, at line 2. In a tiling WM, opening a
# second window narrows foot, foot reflows its scrollback, and the wide logo
# can't un-wrap — so it garbles. There is no foot/fastfetch option to prevent
# that; the only real fix is to redraw. While the terminal is still FRESH (no
# command run yet), reprint the fetch at the new width on every resize; once a
# command has run, resizing behaves normally so scrollback is never disturbed.
if [[ $- == *i* ]]; then
  _ff_fresh=1
  autoload -Uz add-zsh-hook
  _ff_mark_used() { _ff_fresh=0 }
  add-zsh-hook preexec _ff_mark_used
  # zsh calls TRAPWINCH on SIGWINCH after it has updated COLUMNS/LINES.
  TRAPWINCH() {
    if [[ $_ff_fresh == 1 ]] && command -v fastfetch >/dev/null 2>&1; then
      print -rn -- $'\e[3J\e[H\e[2J'   # drop scrollback, home, clear screen
      ff                                # width-aware: stacks when narrow
    fi
    # Redraw the prompt in place (also what p10k wants after a resize).
    zle reset-prompt 2>/dev/null
  }
fi

# >>> grok installer >>>
export PATH="$HOME/.grok/bin:$PATH"
fpath=(~/.grok/completions/zsh $fpath)
autoload -Uz compinit && compinit -C
# <<< grok installer <<<
